### ISSUE TITLE
Add CLI capability

### ISSUE THREAD

**Issue by EthanThatOneKid** [NfNitLoop/deno-embedder#7]
A `main` function is exported from `mod.ts`, but is never run.

As a proof of concept, I created a simple CLI script that wraps the `main` function.

Proof-of-concept: <https://github.com/ethanthatonekid/deno-embedder-cli#readme>

```sh
deno run -A https://deno.land/x/embedder_cli/main.ts --mappings="[{\"sourceDir\":\"./.vscode\",\"destDir\":\"./examples/00_vscode\"}]"
```

**Comment by NfNitLoop** [comment]
That `--mappings` argument is a bit gnarly.  

My current recommended way to make your own `embedder.ts` file which can contain both your configuration, and the call to main to kick things off. There's an example here:

https://github.com/NfNitLoop/deno-embedder/blob/main/examples/with-embedder/embedder.ts

The main benefits of that approach:
 * you get type-checking for your configuration in your IDE. (instead of trying to do it in .jsonc or .yaml, and check things after the fact.)
 * You can `deno run ./embedder.ts` instead of a remote URL.
 * If you need to automate configuration (say, auto-discover directories to map) you're already in TypeScript so can just write your own, as long as it outputs the right type to pass to main().

**Comment by EthanThatOneKid** [comment]
> My current recommended way to make your own `embedder.ts` file which can contain both your configuration, and the call to main to kick things off. There's an example here:
> 
> https://github.com/NfNitLoop/deno-embedder/blob/main/examples/with-embedder/embedder.ts
> 
> The main benefits of that approach:
> 
> * you get type-checking for your configuration in your IDE. (instead of trying to do it in .jsonc or .yaml, and check things after the fact.)
> * You can `deno run ./embedder.ts` instead of a remote URL.
> * If you need to automate configuration (say, auto-discover directories to map) you're already in TypeScript so can just write your own, as long as it outputs the right type to pass to main().

Thank you for recommending the `embedder.ts` approach, it's very helpful. Would it be possible to also include a script for running the embedder directly from the command line for convenience? This could be helpful for those who are familiar with the script's functionality and want to streamline their workflow. If this doesn't align with your project vision, no worries. Thanks again for your work!

**Comment by EthanThatOneKid** [comment]
> That `--mappings` argument is a bit gnarly.

A less gnarly argument could be a path to the mappings JSON data.

```sh
deno run -A https://deno.land/x/embedder_cli/main.ts --mappings="mappings.json"
```

**Comment by NfNitLoop** [comment]
Closing this ticket.  You can run embedder.ts as a CLI. 

See: https://github.com/NfNitLoop/deno-embedder/blob/main/examples/with-embedder/embedder.ts
